# AUTO-GENERATED FILE — Regenerate with: make gen
"""Lazy-import manifest — single source of truth for flext_cli.services.__init__.py.

Generated by ``make gen``. The package initializer consumes only this module for
lazy (PEP 562) import access; sibling ``__all__`` discovery is the upstream source.
"""

from __future__ import annotations

LAZY_MODULES: dict[str, tuple[str, ...]] = {
    "._prompts_parts.flextcliprompts_part_03": ("FlextCliPrompts",),
    "._prompts_parts.flextcliprompts_support": ("FlextCliPromptsSupport",),
    ".auth": ("FlextCliAuth",),
    ".cli": ("FlextCliCli",),
    ".cli_params": ("FlextCliCommonParams",),
    ".cmd": ("FlextCliCmd",),
    ".file_tools": ("FlextCliFileTools",),
    ".formatters": ("FlextCliFormatters",),
    ".output": ("FlextCliOutput",),
    ".pipeline": ("FlextCliPipeline",),
    ".rules": ("FlextCliRules",),
    ".runtime": ("FlextCliRuntime",),
    ".tables": ("FlextCliTables",),
}


LAZY_ALIAS_GROUPS: dict[str, tuple[tuple[str, str], ...]] = {}


CHILD_MODULE_PATHS: tuple[str, ...] = ("._cli_parts", "._prompts_parts")


EXCLUDED_LAZY_NAMES: tuple[str, ...] = ()


PUBLIC_EXPORTS: tuple[str, ...] = (
    "FlextCliAuth",
    "FlextCliCli",
    "FlextCliCmd",
    "FlextCliCommonParams",
    "FlextCliFileTools",
    "FlextCliFormatters",
    "FlextCliOutput",
    "FlextCliPipeline",
    "FlextCliPrompts",
    "FlextCliPromptsSupport",
    "FlextCliRules",
    "FlextCliRuntime",
    "FlextCliTables",
    "_cli_parts",
    "_prompts_parts",
)
