# AUTO-GENERATED FILE — DO NOT EDIT MANUALLY.
# Regenerate with: make codegen
#
"""Tests package."""

from __future__ import annotations

from typing import TYPE_CHECKING

from flext_core.lazy import cleanup_submodule_namespace, lazy_getattr

if TYPE_CHECKING:
    from flext_core.typings import FlextTypes

    from flext_cli import d, e, h, r, s, x

    from . import integration as integration, unit as unit
    from .base import TestsCliServiceBase
    from .conftest import (
        CliCommandFactory,
        CliSessionFactory,
        DebugInfoFactory,
        Examples,
        InfoTuples,
        LoggingConfigFactory,
        clean_flext_container,
        cli_command_factory,
        cli_runner,
        cli_session_factory,
        debug_info_factory,
        fixture_config_file,
        fixture_data_csv,
        fixture_data_json,
        flext_cli_api,
        flext_cli_cmd,
        flext_cli_commands,
        flext_cli_config,
        flext_cli_constants,
        flext_cli_context,
        flext_cli_core,
        flext_cli_debug,
        flext_cli_file_tools,
        flext_cli_mixins,
        flext_cli_models,
        flext_cli_output,
        flext_cli_prompts,
        flext_cli_protocols,
        flext_cli_utilities,
        flext_test_docker,
        input_exception_simulator,
        input_simulator,
        load_fixture_config,
        load_fixture_data,
        logging_config_factory,
        mock_env_vars,
        password_simulator,
        pytest_collection_modifyitems,
        pytest_configure,
        reset_singletons,
        sample_command_data,
        sample_config_data,
        sample_file_data,
        temp_csv_file,
        temp_dir,
        temp_file,
        temp_json_file,
        temp_yaml_file,
    )
    from .constants import TestsFlextCliConstants, TestsFlextCliConstants as c
    from .integration import TestsCliWorkflowIntegration
    from .models import (
        AliasedConfig,
        AliasedParams,
        ApiResponse,
        AppParams,
        BooleanFlagsConfig,
        ChoiceTestCaseDict,
        CliCommandInput,
        CliSessionInput,
        ConfirmTestCaseDict,
        ConnectionConfig,
        EnvironmentConfig,
        ForbidExtraParams,
        FullAppParams,
        NestedModelConfig,
        OptionalLiteralConfig,
        PrintStatusCase,
        RequiredFieldsParams,
        ScalarConfigRestore,
        SimpleParams,
        StrictParams,
        TestsFlextCliModels,
        TestsFlextCliModels as m,
        TextTestCaseDict,
        UserData,
        ValidatedConfig,
    )
    from .protocols import TestsCliProtocols, TestsCliProtocols as p
    from .typings import T, T_co, T_contra, TestsCliTypes, TestsCliTypes as t, tt
    from .unit import (
        ConfigErrorScenario,
        ConfigOperation,
        ConfigParam,
        ConfigTestFactory,
        ConfigTestScenario,
        ConfigTestType,
        TestsCliCli,
        TestsCliCliExtended,
        TestsCliCmd,
        TestsCliCommands,
        TestsCliCommonParams,
        TestsCliComprehensiveModels,
        TestsCliConfigBasics,
        TestsCliConfigComputedFields,
        TestsCliConfigConcurrency,
        TestsCliConfigEdgeCases,
        TestsCliConfigFilesOperations,
        TestsCliConfigIntegration,
        TestsCliConfigLogging,
        TestsCliConfigMemory,
        TestsCliConfigModelIntegration,
        TestsCliConfigService,
        TestsCliConfigValidation,
        TestsCliConstants,
        TestsCliDebug,
        TestsCliLoggingConfig,
        TestsCliModelCommandComprehensive,
        TestsCliModelFactories,
        TestsCliModelSerialization,
        TestsCliModelValidation,
        TestsCliPerformanceAutomated,
        TestsCliPrompts,
        TestsCliRailwayPatternExample,
        TestsCliTypings,
        TestsCliVersion,
        TypingTestCase,
        TypingTestType,
        create_cli_app,
        create_decorated_command,
        create_test_config,
        reset_config_singleton,
        test_auth_options_include_expected_env_vars,
        test_connection_options_defaults_are_exposed,
        test_edit_config_outer_exception_path,
        test_edit_config_success_logs_and_returns_ok,
        test_get_config_info_failure_on_exception,
        test_get_config_value_outer_exception_path,
        test_normalize_union_type_returns_annotation_for_none_only_args,
        test_normalize_union_type_returns_none_for_empty_normalized_list,
        test_normalize_union_type_returns_none_when_inner_is_none,
        test_output_options_expose_format_output_and_verbosity,
        test_parse_kwargs_skips_missing_enum_field_key,
        test_print_status_exception_path,
        test_process_fail_and_collect_paths,
        test_process_mapping_fail_and_collect_paths,
        test_prompt_choice_covers_required_default_and_exception,
        test_prompt_confirmation_handles_exception_from_record,
        test_prompt_logs_input_when_not_test_env,
        test_read_confirmation_input_paths,
        test_read_selection_paths,
        test_select_from_options_logs_successful_selection,
        test_set_config_value_outer_exception_path,
        test_show_config_failure_when_info_result_is_failure,
        test_show_config_outer_exception_path,
        test_show_config_paths_failure_on_exception,
        test_validate_config_failure_on_exception,
        test_validate_required_string_raises_value_error,
        test_validated_with_result_returns_failure_on_validation_error,
        test_validation_state_requires_criteria,
        test_validation_v_uses_custom_message_on_empty_failure,
    )
    from .utilities import TestsCliUtilities, TestsCliUtilities as u

_LAZY_IMPORTS: dict[str, tuple[str, str]] = {
    "AliasedConfig": ("tests.models", "AliasedConfig"),
    "AliasedParams": ("tests.models", "AliasedParams"),
    "ApiResponse": ("tests.models", "ApiResponse"),
    "AppParams": ("tests.models", "AppParams"),
    "BooleanFlagsConfig": ("tests.models", "BooleanFlagsConfig"),
    "ChoiceTestCaseDict": ("tests.models", "ChoiceTestCaseDict"),
    "CliCommandFactory": ("tests.conftest", "CliCommandFactory"),
    "CliCommandInput": ("tests.models", "CliCommandInput"),
    "CliSessionFactory": ("tests.conftest", "CliSessionFactory"),
    "CliSessionInput": ("tests.models", "CliSessionInput"),
    "ConfigErrorScenario": ("tests.unit", "ConfigErrorScenario"),
    "ConfigOperation": ("tests.unit", "ConfigOperation"),
    "ConfigParam": ("tests.unit", "ConfigParam"),
    "ConfigTestFactory": ("tests.unit", "ConfigTestFactory"),
    "ConfigTestScenario": ("tests.unit", "ConfigTestScenario"),
    "ConfigTestType": ("tests.unit", "ConfigTestType"),
    "ConfirmTestCaseDict": ("tests.models", "ConfirmTestCaseDict"),
    "ConnectionConfig": ("tests.models", "ConnectionConfig"),
    "DebugInfoFactory": ("tests.conftest", "DebugInfoFactory"),
    "EnvironmentConfig": ("tests.models", "EnvironmentConfig"),
    "Examples": ("tests.conftest", "Examples"),
    "ForbidExtraParams": ("tests.models", "ForbidExtraParams"),
    "FullAppParams": ("tests.models", "FullAppParams"),
    "InfoTuples": ("tests.conftest", "InfoTuples"),
    "LoggingConfigFactory": ("tests.conftest", "LoggingConfigFactory"),
    "NestedModelConfig": ("tests.models", "NestedModelConfig"),
    "OptionalLiteralConfig": ("tests.models", "OptionalLiteralConfig"),
    "PrintStatusCase": ("tests.models", "PrintStatusCase"),
    "RequiredFieldsParams": ("tests.models", "RequiredFieldsParams"),
    "ScalarConfigRestore": ("tests.models", "ScalarConfigRestore"),
    "SimpleParams": ("tests.models", "SimpleParams"),
    "StrictParams": ("tests.models", "StrictParams"),
    "T": ("tests.typings", "T"),
    "T_co": ("tests.typings", "T_co"),
    "T_contra": ("tests.typings", "T_contra"),
    "TestsCliCli": ("tests.unit", "TestsCliCli"),
    "TestsCliCliExtended": ("tests.unit", "TestsCliCliExtended"),
    "TestsCliCmd": ("tests.unit", "TestsCliCmd"),
    "TestsCliCommands": ("tests.unit", "TestsCliCommands"),
    "TestsCliCommonParams": ("tests.unit", "TestsCliCommonParams"),
    "TestsCliComprehensiveModels": ("tests.unit", "TestsCliComprehensiveModels"),
    "TestsCliConfigBasics": ("tests.unit", "TestsCliConfigBasics"),
    "TestsCliConfigComputedFields": ("tests.unit", "TestsCliConfigComputedFields"),
    "TestsCliConfigConcurrency": ("tests.unit", "TestsCliConfigConcurrency"),
    "TestsCliConfigEdgeCases": ("tests.unit", "TestsCliConfigEdgeCases"),
    "TestsCliConfigFilesOperations": ("tests.unit", "TestsCliConfigFilesOperations"),
    "TestsCliConfigIntegration": ("tests.unit", "TestsCliConfigIntegration"),
    "TestsCliConfigLogging": ("tests.unit", "TestsCliConfigLogging"),
    "TestsCliConfigMemory": ("tests.unit", "TestsCliConfigMemory"),
    "TestsCliConfigModelIntegration": ("tests.unit", "TestsCliConfigModelIntegration"),
    "TestsCliConfigService": ("tests.unit", "TestsCliConfigService"),
    "TestsCliConfigValidation": ("tests.unit", "TestsCliConfigValidation"),
    "TestsCliConstants": ("tests.unit", "TestsCliConstants"),
    "TestsCliDebug": ("tests.unit", "TestsCliDebug"),
    "TestsCliLoggingConfig": ("tests.unit", "TestsCliLoggingConfig"),
    "TestsCliModelCommandComprehensive": (
        "tests.unit",
        "TestsCliModelCommandComprehensive",
    ),
    "TestsCliModelFactories": ("tests.unit", "TestsCliModelFactories"),
    "TestsCliModelSerialization": ("tests.unit", "TestsCliModelSerialization"),
    "TestsCliModelValidation": ("tests.unit", "TestsCliModelValidation"),
    "TestsCliPerformanceAutomated": ("tests.unit", "TestsCliPerformanceAutomated"),
    "TestsCliPrompts": ("tests.unit", "TestsCliPrompts"),
    "TestsCliProtocols": ("tests.protocols", "TestsCliProtocols"),
    "TestsCliRailwayPatternExample": ("tests.unit", "TestsCliRailwayPatternExample"),
    "TestsCliServiceBase": ("tests.base", "TestsCliServiceBase"),
    "TestsCliTypes": ("tests.typings", "TestsCliTypes"),
    "TestsCliTypings": ("tests.unit", "TestsCliTypings"),
    "TestsCliUtilities": ("tests.utilities", "TestsCliUtilities"),
    "TestsCliVersion": ("tests.unit", "TestsCliVersion"),
    "TestsCliWorkflowIntegration": ("tests.integration", "TestsCliWorkflowIntegration"),
    "TestsFlextCliConstants": ("tests.constants", "TestsFlextCliConstants"),
    "TestsFlextCliModels": ("tests.models", "TestsFlextCliModels"),
    "TextTestCaseDict": ("tests.models", "TextTestCaseDict"),
    "TypingTestCase": ("tests.unit", "TypingTestCase"),
    "TypingTestType": ("tests.unit", "TypingTestType"),
    "UserData": ("tests.models", "UserData"),
    "ValidatedConfig": ("tests.models", "ValidatedConfig"),
    "c": ("tests.constants", "TestsFlextCliConstants"),
    "clean_flext_container": ("tests.conftest", "clean_flext_container"),
    "cli_command_factory": ("tests.conftest", "cli_command_factory"),
    "cli_runner": ("tests.conftest", "cli_runner"),
    "cli_session_factory": ("tests.conftest", "cli_session_factory"),
    "create_cli_app": ("tests.unit", "create_cli_app"),
    "create_decorated_command": ("tests.unit", "create_decorated_command"),
    "create_test_config": ("tests.unit", "create_test_config"),
    "d": ("flext_cli", "d"),
    "debug_info_factory": ("tests.conftest", "debug_info_factory"),
    "e": ("flext_cli", "e"),
    "fixture_config_file": ("tests.conftest", "fixture_config_file"),
    "fixture_data_csv": ("tests.conftest", "fixture_data_csv"),
    "fixture_data_json": ("tests.conftest", "fixture_data_json"),
    "flext_cli_api": ("tests.conftest", "flext_cli_api"),
    "flext_cli_cmd": ("tests.conftest", "flext_cli_cmd"),
    "flext_cli_commands": ("tests.conftest", "flext_cli_commands"),
    "flext_cli_config": ("tests.conftest", "flext_cli_config"),
    "flext_cli_constants": ("tests.conftest", "flext_cli_constants"),
    "flext_cli_context": ("tests.conftest", "flext_cli_context"),
    "flext_cli_core": ("tests.conftest", "flext_cli_core"),
    "flext_cli_debug": ("tests.conftest", "flext_cli_debug"),
    "flext_cli_file_tools": ("tests.conftest", "flext_cli_file_tools"),
    "flext_cli_mixins": ("tests.conftest", "flext_cli_mixins"),
    "flext_cli_models": ("tests.conftest", "flext_cli_models"),
    "flext_cli_output": ("tests.conftest", "flext_cli_output"),
    "flext_cli_prompts": ("tests.conftest", "flext_cli_prompts"),
    "flext_cli_protocols": ("tests.conftest", "flext_cli_protocols"),
    "flext_cli_utilities": ("tests.conftest", "flext_cli_utilities"),
    "flext_test_docker": ("tests.conftest", "flext_test_docker"),
    "h": ("flext_cli", "h"),
    "input_exception_simulator": ("tests.conftest", "input_exception_simulator"),
    "input_simulator": ("tests.conftest", "input_simulator"),
    "integration": ("tests.integration", ""),
    "load_fixture_config": ("tests.conftest", "load_fixture_config"),
    "load_fixture_data": ("tests.conftest", "load_fixture_data"),
    "logging_config_factory": ("tests.conftest", "logging_config_factory"),
    "m": ("tests.models", "TestsFlextCliModels"),
    "mock_env_vars": ("tests.conftest", "mock_env_vars"),
    "p": ("tests.protocols", "TestsCliProtocols"),
    "password_simulator": ("tests.conftest", "password_simulator"),
    "pytest_collection_modifyitems": (
        "tests.conftest",
        "pytest_collection_modifyitems",
    ),
    "pytest_configure": ("tests.conftest", "pytest_configure"),
    "r": ("flext_cli", "r"),
    "reset_config_singleton": ("tests.unit", "reset_config_singleton"),
    "reset_singletons": ("tests.conftest", "reset_singletons"),
    "s": ("flext_cli", "s"),
    "sample_command_data": ("tests.conftest", "sample_command_data"),
    "sample_config_data": ("tests.conftest", "sample_config_data"),
    "sample_file_data": ("tests.conftest", "sample_file_data"),
    "t": ("tests.typings", "TestsCliTypes"),
    "temp_csv_file": ("tests.conftest", "temp_csv_file"),
    "temp_dir": ("tests.conftest", "temp_dir"),
    "temp_file": ("tests.conftest", "temp_file"),
    "temp_json_file": ("tests.conftest", "temp_json_file"),
    "temp_yaml_file": ("tests.conftest", "temp_yaml_file"),
    "test_auth_options_include_expected_env_vars": (
        "tests.unit",
        "test_auth_options_include_expected_env_vars",
    ),
    "test_connection_options_defaults_are_exposed": (
        "tests.unit",
        "test_connection_options_defaults_are_exposed",
    ),
    "test_edit_config_outer_exception_path": (
        "tests.unit",
        "test_edit_config_outer_exception_path",
    ),
    "test_edit_config_success_logs_and_returns_ok": (
        "tests.unit",
        "test_edit_config_success_logs_and_returns_ok",
    ),
    "test_get_config_info_failure_on_exception": (
        "tests.unit",
        "test_get_config_info_failure_on_exception",
    ),
    "test_get_config_value_outer_exception_path": (
        "tests.unit",
        "test_get_config_value_outer_exception_path",
    ),
    "test_normalize_union_type_returns_annotation_for_none_only_args": (
        "tests.unit",
        "test_normalize_union_type_returns_annotation_for_none_only_args",
    ),
    "test_normalize_union_type_returns_none_for_empty_normalized_list": (
        "tests.unit",
        "test_normalize_union_type_returns_none_for_empty_normalized_list",
    ),
    "test_normalize_union_type_returns_none_when_inner_is_none": (
        "tests.unit",
        "test_normalize_union_type_returns_none_when_inner_is_none",
    ),
    "test_output_options_expose_format_output_and_verbosity": (
        "tests.unit",
        "test_output_options_expose_format_output_and_verbosity",
    ),
    "test_parse_kwargs_skips_missing_enum_field_key": (
        "tests.unit",
        "test_parse_kwargs_skips_missing_enum_field_key",
    ),
    "test_print_status_exception_path": (
        "tests.unit",
        "test_print_status_exception_path",
    ),
    "test_process_fail_and_collect_paths": (
        "tests.unit",
        "test_process_fail_and_collect_paths",
    ),
    "test_process_mapping_fail_and_collect_paths": (
        "tests.unit",
        "test_process_mapping_fail_and_collect_paths",
    ),
    "test_prompt_choice_covers_required_default_and_exception": (
        "tests.unit",
        "test_prompt_choice_covers_required_default_and_exception",
    ),
    "test_prompt_confirmation_handles_exception_from_record": (
        "tests.unit",
        "test_prompt_confirmation_handles_exception_from_record",
    ),
    "test_prompt_logs_input_when_not_test_env": (
        "tests.unit",
        "test_prompt_logs_input_when_not_test_env",
    ),
    "test_read_confirmation_input_paths": (
        "tests.unit",
        "test_read_confirmation_input_paths",
    ),
    "test_read_selection_paths": ("tests.unit", "test_read_selection_paths"),
    "test_select_from_options_logs_successful_selection": (
        "tests.unit",
        "test_select_from_options_logs_successful_selection",
    ),
    "test_set_config_value_outer_exception_path": (
        "tests.unit",
        "test_set_config_value_outer_exception_path",
    ),
    "test_show_config_failure_when_info_result_is_failure": (
        "tests.unit",
        "test_show_config_failure_when_info_result_is_failure",
    ),
    "test_show_config_outer_exception_path": (
        "tests.unit",
        "test_show_config_outer_exception_path",
    ),
    "test_show_config_paths_failure_on_exception": (
        "tests.unit",
        "test_show_config_paths_failure_on_exception",
    ),
    "test_validate_config_failure_on_exception": (
        "tests.unit",
        "test_validate_config_failure_on_exception",
    ),
    "test_validate_required_string_raises_value_error": (
        "tests.unit",
        "test_validate_required_string_raises_value_error",
    ),
    "test_validated_with_result_returns_failure_on_validation_error": (
        "tests.unit",
        "test_validated_with_result_returns_failure_on_validation_error",
    ),
    "test_validation_state_requires_criteria": (
        "tests.unit",
        "test_validation_state_requires_criteria",
    ),
    "test_validation_v_uses_custom_message_on_empty_failure": (
        "tests.unit",
        "test_validation_v_uses_custom_message_on_empty_failure",
    ),
    "tt": ("tests.typings", "tt"),
    "u": ("tests.utilities", "TestsCliUtilities"),
    "unit": ("tests.unit", ""),
    "x": ("flext_cli", "x"),
}

__all__ = [
    "AliasedConfig",
    "AliasedParams",
    "ApiResponse",
    "AppParams",
    "BooleanFlagsConfig",
    "ChoiceTestCaseDict",
    "CliCommandFactory",
    "CliCommandInput",
    "CliSessionFactory",
    "CliSessionInput",
    "ConfigErrorScenario",
    "ConfigOperation",
    "ConfigParam",
    "ConfigTestFactory",
    "ConfigTestScenario",
    "ConfigTestType",
    "ConfirmTestCaseDict",
    "ConnectionConfig",
    "DebugInfoFactory",
    "EnvironmentConfig",
    "Examples",
    "ForbidExtraParams",
    "FullAppParams",
    "InfoTuples",
    "LoggingConfigFactory",
    "NestedModelConfig",
    "OptionalLiteralConfig",
    "PrintStatusCase",
    "RequiredFieldsParams",
    "ScalarConfigRestore",
    "SimpleParams",
    "StrictParams",
    "T",
    "T_co",
    "T_contra",
    "TestsCliCli",
    "TestsCliCliExtended",
    "TestsCliCmd",
    "TestsCliCommands",
    "TestsCliCommonParams",
    "TestsCliComprehensiveModels",
    "TestsCliConfigBasics",
    "TestsCliConfigComputedFields",
    "TestsCliConfigConcurrency",
    "TestsCliConfigEdgeCases",
    "TestsCliConfigFilesOperations",
    "TestsCliConfigIntegration",
    "TestsCliConfigLogging",
    "TestsCliConfigMemory",
    "TestsCliConfigModelIntegration",
    "TestsCliConfigService",
    "TestsCliConfigValidation",
    "TestsCliConstants",
    "TestsCliDebug",
    "TestsCliLoggingConfig",
    "TestsCliModelCommandComprehensive",
    "TestsCliModelFactories",
    "TestsCliModelSerialization",
    "TestsCliModelValidation",
    "TestsCliPerformanceAutomated",
    "TestsCliPrompts",
    "TestsCliProtocols",
    "TestsCliRailwayPatternExample",
    "TestsCliServiceBase",
    "TestsCliTypes",
    "TestsCliTypings",
    "TestsCliUtilities",
    "TestsCliVersion",
    "TestsCliWorkflowIntegration",
    "TestsFlextCliConstants",
    "TestsFlextCliModels",
    "TextTestCaseDict",
    "TypingTestCase",
    "TypingTestType",
    "UserData",
    "ValidatedConfig",
    "c",
    "clean_flext_container",
    "cli_command_factory",
    "cli_runner",
    "cli_session_factory",
    "create_cli_app",
    "create_decorated_command",
    "create_test_config",
    "d",
    "debug_info_factory",
    "e",
    "fixture_config_file",
    "fixture_data_csv",
    "fixture_data_json",
    "flext_cli_api",
    "flext_cli_cmd",
    "flext_cli_commands",
    "flext_cli_config",
    "flext_cli_constants",
    "flext_cli_context",
    "flext_cli_core",
    "flext_cli_debug",
    "flext_cli_file_tools",
    "flext_cli_mixins",
    "flext_cli_models",
    "flext_cli_output",
    "flext_cli_prompts",
    "flext_cli_protocols",
    "flext_cli_utilities",
    "flext_test_docker",
    "h",
    "input_exception_simulator",
    "input_simulator",
    "integration",
    "load_fixture_config",
    "load_fixture_data",
    "logging_config_factory",
    "m",
    "mock_env_vars",
    "p",
    "password_simulator",
    "pytest_collection_modifyitems",
    "pytest_configure",
    "r",
    "reset_config_singleton",
    "reset_singletons",
    "s",
    "sample_command_data",
    "sample_config_data",
    "sample_file_data",
    "t",
    "temp_csv_file",
    "temp_dir",
    "temp_file",
    "temp_json_file",
    "temp_yaml_file",
    "test_auth_options_include_expected_env_vars",
    "test_connection_options_defaults_are_exposed",
    "test_edit_config_outer_exception_path",
    "test_edit_config_success_logs_and_returns_ok",
    "test_get_config_info_failure_on_exception",
    "test_get_config_value_outer_exception_path",
    "test_normalize_union_type_returns_annotation_for_none_only_args",
    "test_normalize_union_type_returns_none_for_empty_normalized_list",
    "test_normalize_union_type_returns_none_when_inner_is_none",
    "test_output_options_expose_format_output_and_verbosity",
    "test_parse_kwargs_skips_missing_enum_field_key",
    "test_print_status_exception_path",
    "test_process_fail_and_collect_paths",
    "test_process_mapping_fail_and_collect_paths",
    "test_prompt_choice_covers_required_default_and_exception",
    "test_prompt_confirmation_handles_exception_from_record",
    "test_prompt_logs_input_when_not_test_env",
    "test_read_confirmation_input_paths",
    "test_read_selection_paths",
    "test_select_from_options_logs_successful_selection",
    "test_set_config_value_outer_exception_path",
    "test_show_config_failure_when_info_result_is_failure",
    "test_show_config_outer_exception_path",
    "test_show_config_paths_failure_on_exception",
    "test_validate_config_failure_on_exception",
    "test_validate_required_string_raises_value_error",
    "test_validated_with_result_returns_failure_on_validation_error",
    "test_validation_state_requires_criteria",
    "test_validation_v_uses_custom_message_on_empty_failure",
    "tt",
    "u",
    "unit",
    "x",
]


def __getattr__(name: str) -> FlextTypes.ModuleExport:
    """Lazy-load module attributes on first access (PEP 562)."""
    return lazy_getattr(name, _LAZY_IMPORTS, globals(), __name__)


def __dir__() -> list[str]:
    """Return list of available attributes for dir() and autocomplete."""
    return sorted(__all__)


cleanup_submodule_namespace(__name__, _LAZY_IMPORTS)
