# AUTO-GENERATED FILE — Regenerate with: make gen
"""Tests package."""

from __future__ import annotations

import typing as _t

from flext_core.lazy import install_lazy_exports
from tests._exports import TESTS_FLEXT_CLI_LAZY_IMPORTS

if _t.TYPE_CHECKING:
    from tests._exports_typing import *

install_lazy_exports(__name__, globals(), TESTS_FLEXT_CLI_LAZY_IMPORTS)

__all__: list[str] = [
    "TestsFlextCliAuthUtilsCov",
    "TestsFlextCliCaptureLogPrompts",
    "TestsFlextCliCmd",
    "TestsFlextCliCmdCov",
    "TestsFlextCliCmdRuntimeValidationBranchCov",
    "TestsFlextCliCommandsUtilsCov",
    "TestsFlextCliCommonParams",
    "TestsFlextCliConstants",
    "TestsFlextCliConstantsUnit",
    "TestsFlextCliConversionCov",
    "TestsFlextCliExampleModelsUtilitiesCov",
    "TestsFlextCliExamplesSmoke",
    "TestsFlextCliFailingLogPrompts",
    "TestsFlextCliFilesCov",
    "TestsFlextCliFormattersCov",
    "TestsFlextCliJsonCov",
    "TestsFlextCliMatchingCov",
    "TestsFlextCliModelCommandsCov",
    "TestsFlextCliModels",
    "TestsFlextCliOptionsPublicCoverage",
    "TestsFlextCliOptionsUtilsCov",
    "TestsFlextCliOutputCov",
    "TestsFlextCliParamsBranchCov",
    "TestsFlextCliPipeline",
    "TestsFlextCliPrompts",
    "TestsFlextCliPromptsCov",
    "TestsFlextCliProtocols",
    "TestsFlextCliProtocolsUnit",
    "TestsFlextCliPublicContractsCoverage",
    "TestsFlextCliRulesCov",
    "TestsFlextCliRuntimeUtilitiesCore",
    "TestsFlextCliRuntimeUtilitiesExtra",
    "TestsFlextCliScriptedPrompts",
    "TestsFlextCliService",
    "TestsFlextCliServiceBase",
    "TestsFlextCliServiceBaseBehavior",
    "TestsFlextCliServicesAuthBranchCov",
    "TestsFlextCliServicesAuthCov",
    "TestsFlextCliServicesFormattersCov",
    "TestsFlextCliServicesOutputCov",
    "TestsFlextCliServicesTablesBranchCov",
    "TestsFlextCliServicesTablesCov",
    "TestsFlextCliSettings",
    "TestsFlextCliSettingsUnit",
    "TestsFlextCliTableUtilsCov",
    "TestsFlextCliTables",
    "TestsFlextCliTablesBranchCov",
    "TestsFlextCliTomlSyncCoverage",
    "TestsFlextCliTomlUtilities",
    "TestsFlextCliTomlUtilsCov",
    "TestsFlextCliTypes",
    "TestsFlextCliTypesUnit",
    "TestsFlextCliUtilities",
    "TestsFlextCliUtilitiesCov",
    "TestsFlextCliVersion",
    "TestsFlextCliYamlCov",
    "c",
    "d",
    "e",
    "h",
    "m",
    "make_capture_prompts",
    "make_failing_prompts",
    "make_prompts",
    "p",
    "r",
    "reset_settings",
    "s",
    "t",
    "td",
    "tf",
    "tk",
    "tm",
    "tv",
    "u",
    "x",
]
