# AUTO-GENERATED FILE — Regenerate with: make gen
"""Lazy-import manifest — single source of truth for flext_cli._models.__init__.py.

Generated by ``make gen``. The package initializer consumes only this module for
lazy (PEP 562) import access; sibling ``__all__`` discovery is the upstream source.
"""

from __future__ import annotations

LAZY_MODULES: dict[str, tuple[str, ...]] = {
    "._base_parts.flextclimodelsbase_part_07": ("FlextCliModelsBase",),
    "._test_tmp": ("X",),
    ".config": ("FlextCliConfigModels",),
    ".pipeline": ("FlextCliModelsPipeline",),
    ".rules": ("FlextCliModelsRules",),
    ".template": ("FlextCliModelsTemplate",),
    ".xlsx": ("FlextCliModelsXlsx",),
    ".xlsx_archive": ("FlextCliModelsXlsxArchive",),
    ".xlsx_cells": ("FlextCliModelsXlsxCells",),
    ".xlsx_layout": ("FlextCliModelsXlsxLayout",),
    ".xlsx_recalc": ("FlextCliModelsXlsxRecalc",),
    ".xlsx_rules": ("FlextCliModelsXlsxRules",),
    ".xlsx_snapshot": ("FlextCliModelsXlsxSnapshot",),
    ".xlsx_style_catalog": ("FlextCliModelsXlsxStyleCatalog",),
    ".xlsx_style_fills": ("FlextCliModelsXlsxStyleFills",),
    ".xlsx_style_primitives": ("FlextCliModelsXlsxStylePrimitives",),
    ".xlsx_styles": ("FlextCliModelsXlsxStyles",),
    ".xlsx_tables": ("FlextCliModelsXlsxTables",),
    ".xlsx_validation": ("FlextCliModelsXlsxValidation",),
    ".xlsx_workbook": ("FlextCliModelsXlsxWorkbook",),
}


LAZY_ALIAS_GROUPS: dict[str, tuple[tuple[str, str], ...]] = {}


CHILD_MODULE_PATHS: tuple[str, ...] = ("._base_parts",)


EXCLUDED_LAZY_NAMES: tuple[str, ...] = ()


PUBLIC_EXPORTS: tuple[str, ...] = (
    "FlextCliConfigModels",
    "FlextCliModelsBase",
    "FlextCliModelsPipeline",
    "FlextCliModelsRules",
    "FlextCliModelsTemplate",
    "FlextCliModelsXlsx",
    "FlextCliModelsXlsxArchive",
    "FlextCliModelsXlsxCells",
    "FlextCliModelsXlsxLayout",
    "FlextCliModelsXlsxRecalc",
    "FlextCliModelsXlsxRules",
    "FlextCliModelsXlsxSnapshot",
    "FlextCliModelsXlsxStyleCatalog",
    "FlextCliModelsXlsxStyleFills",
    "FlextCliModelsXlsxStylePrimitives",
    "FlextCliModelsXlsxStyles",
    "FlextCliModelsXlsxTables",
    "FlextCliModelsXlsxValidation",
    "FlextCliModelsXlsxWorkbook",
    "X",
    "_base_parts",
)
