# AUTO-GENERATED FILE — Regenerate with: make gen
"""Lazy-import manifest — single source of truth for flext_cli._utilities.__init__.py.

Generated by ``make gen``. The package initializer consumes only this module for
lazy (PEP 562) import access; sibling ``__all__`` discovery is the upstream source.
"""

from __future__ import annotations

LAZY_MODULES: dict[str, tuple[str, ...]] = {
    "._cli_namespace": ("FlextCliUtilitiesCli",),
    "._file_test_helper_parts.flextcliutilitiesfiletesthelpersmixin_part_04": (
        "FlextCliUtilitiesFileTestHelpersMixin",
    ),
    "._files_parts.flextcliutilitiesfiles_part_04": ("FlextCliUtilitiesFiles",),
    "._json_parts.flextcliutilitiesjson_part_03": ("FlextCliUtilitiesJson",),
    "._options_parts.flextcliutilitiesoptionbuilder_part_01": (
        "FlextCliUtilitiesOptionBuilder",
    ),
    "._options_parts.flextcliutilitiesoptions_part_02": ("FlextCliUtilitiesOptions",),
    "._rules_parts.flextcliutilitiesrules_part_03": ("FlextCliUtilitiesRules",),
    "._toml_parts.flextcliutilitiestoml_part_07": ("FlextCliUtilitiesToml",),
    "._yaml_roundtrip_parts.flextcliutilitiesyamlroundtrip_part_02": (
        "FlextCliUtilitiesYamlRoundtrip",
    ),
    ".auth": ("FlextCliUtilitiesAuth",),
    ".cmd": ("FlextCliUtilitiesCmd",),
    ".commands": ("FlextCliUtilitiesCommands",),
    ".config": ("FlextCliUtilitiesConfig",),
    ".conversion": ("FlextCliUtilitiesConversion",),
    ".formatters": ("FlextCliUtilitiesFormatters",),
    ".framework": ("FlextCliUtilitiesFramework",),
    ".matching": ("FlextCliUtilitiesMatching",),
    ".model_commands": ("FlextCliUtilitiesModelCommands",),
    ".output": ("FlextCliUtilitiesOutput",),
    ".params": ("FlextCliUtilitiesParams",),
    ".pipeline": ("FlextCliUtilitiesPipeline",),
    ".processes": ("FlextCliUtilitiesProcesses",),
    ".prompts": ("FlextCliUtilitiesPrompts",),
    ".runtime": ("FlextCliUtilitiesRuntime",),
    ".settings": ("FlextCliUtilitiesSettings",),
    ".tables": ("FlextCliUtilitiesTables",),
    ".template": ("FlextCliUtilitiesTemplate",),
    ".validation": ("FlextCliUtilitiesValidation",),
    ".yaml": ("FlextCliUtilitiesYaml",),
}


LAZY_ALIAS_GROUPS: dict[str, tuple[tuple[str, str], ...]] = {}


CHILD_MODULE_PATHS: tuple[str, ...] = (
    "._file_test_helper_parts",
    "._files_parts",
    "._json_parts",
    "._options_parts",
    "._rules_parts",
    "._toml_parts",
    "._yaml_roundtrip_parts",
)


EXCLUDED_LAZY_NAMES: tuple[str, ...] = ()


PUBLIC_EXPORTS: tuple[str, ...] = (
    "FlextCliUtilitiesAuth",
    "FlextCliUtilitiesCli",
    "FlextCliUtilitiesCmd",
    "FlextCliUtilitiesCommands",
    "FlextCliUtilitiesConfig",
    "FlextCliUtilitiesConversion",
    "FlextCliUtilitiesFileTestHelpersMixin",
    "FlextCliUtilitiesFiles",
    "FlextCliUtilitiesFormatters",
    "FlextCliUtilitiesFramework",
    "FlextCliUtilitiesJson",
    "FlextCliUtilitiesMatching",
    "FlextCliUtilitiesModelCommands",
    "FlextCliUtilitiesOptionBuilder",
    "FlextCliUtilitiesOptions",
    "FlextCliUtilitiesOutput",
    "FlextCliUtilitiesParams",
    "FlextCliUtilitiesPipeline",
    "FlextCliUtilitiesProcesses",
    "FlextCliUtilitiesPrompts",
    "FlextCliUtilitiesRules",
    "FlextCliUtilitiesRuntime",
    "FlextCliUtilitiesSettings",
    "FlextCliUtilitiesTables",
    "FlextCliUtilitiesTemplate",
    "FlextCliUtilitiesToml",
    "FlextCliUtilitiesValidation",
    "FlextCliUtilitiesYaml",
    "FlextCliUtilitiesYamlRoundtrip",
    "_file_test_helper_parts",
    "_files_parts",
    "_json_parts",
    "_options_parts",
    "_rules_parts",
    "_toml_parts",
    "_yaml_roundtrip_parts",
)
