# AUTO-GENERATED FILE — DO NOT EDIT MANUALLY.
# Regenerate with: make gen
#
"""Examples package."""

from __future__ import annotations

from collections.abc import Mapping, Sequence
from typing import TYPE_CHECKING as _TYPE_CHECKING

from flext_core.lazy import install_lazy_exports

if _TYPE_CHECKING:
    from examples import (
        constants,
        ex_01_getting_started,
        ex_02_output_formatting,
        ex_03_interactive_prompts,
        ex_04_file_operations,
        ex_05_authentication,
        ex_06_configuration,
        ex_07_plugin_system,
        ex_08_shell_interaction,
        ex_09_performance_optimization,
        ex_10_testing_utilities,
        ex_11_complete_integration,
        ex_12_pydantic_driven_cli,
        ex_14_advanced_file_formats,
        ex_15_plugin,
        models,
        protocols,
        typings,
        utilities,
    )
    from examples.constants import ExamplesConstants, ExamplesConstants as c
    from examples.ex_01_getting_started import FlextCliGettingStarted
    from examples.ex_02_output_formatting import (
        advanced_output_example,
        display_database_results,
        display_project_structure,
        display_with_panels,
        export_report,
        monitor_live_metrics,
        process_with_status,
        your_cli_function,
    )
    from examples.ex_03_interactive_prompts import (
        authenticate_user,
        database_setup_wizard,
        delete_database,
        flext_configuration_wizard,
        flext_confirm_prompts,
        flext_numeric_prompts,
        flext_prompt_with_validation,
        get_user_configuration,
        prompts,
        select_environment,
        validate_email_input,
    )
    from examples.ex_04_file_operations import (
        backup_config_files,
        create_processing_summary,
        export_database_report,
        export_multi_format,
        generate_output_files,
        list_project_files,
        load_config_auto_detect,
        load_deployment_config,
        load_user_preferences,
        process_file_pipeline,
        save_deployment_config,
        save_user_preferences,
        show_directory_tree,
        validate_and_import_data,
        validate_and_transform_data,
    )
    from examples.ex_05_authentication import (
        call_authenticated_api,
        complete_auth_workflow,
        get_saved_token,
        login_to_service,
        logout,
        refresh_token_if_needed,
        show_session_info,
        validate_current_token,
        validate_user_credentials,
    )
    from examples.ex_06_configuration import (
        apply_environment_overrides,
        get_cli_settings,
        initialize_services,
        load_application_config,
        load_environment_config,
        load_profile_config,
        show_config_locations,
        show_environment_variables,
        validate_app_config,
    )
    from examples.ex_07_plugin_system import (
        ConfigurablePlugin,
        DataExportPlugin,
        LifecyclePlugin,
        MyAppPluginManager,
        ReportGeneratorPlugin,
        load_plugins_from_directory,
    )
    from examples.ex_08_shell_interaction import (
        CommandHistory,
        InteractiveShell,
        handle_config_command,
        handle_list_command,
        handle_multiline_input,
        handle_status_command,
    )
    from examples.ex_09_performance_optimization import (
        LazyDataLoader,
        demonstrate_caching,
        demonstrate_lazy_loading,
        efficient_cli_usage,
        efficient_table_display,
        expensive_calculation,
        process_large_dataset,
        stream_large_file,
    )
    from examples.ex_10_testing_utilities import (
        full_workflow_command,
        interactive_command,
        my_cli_command,
        risky_operation,
        save_config_command,
        test_cli_command,
        test_error_scenarios,
        test_file_operations,
        test_integration,
        test_interactive_command,
    )
    from examples.ex_11_complete_integration import (
        DataManagerCLI,
        process_with_railway_pattern,
    )
    from examples.ex_12_pydantic_driven_cli import (
        convert_and_validate_with_pydantic,
        create_database_config_from_cli,
        demonstrate_auto_cli_generation,
        demonstrate_nested_models,
        deploy_application,
        execute_deploy_from_cli,
        perform_connection_test,
        show_common_cli_params,
        validate_business_rules,
        validate_required_fields,
    )
    from examples.ex_14_advanced_file_formats import (
        copy_file_with_verification,
        export_data_multi_format,
        export_to_csv,
        import_from_csv,
        load_any_format_file,
        main,
        process_binary_file,
        process_text_file,
    )
    from examples.ex_15_plugin import (
        DataProcessorPlugin,
        ExamplePlugin,
        demonstrate_plugin_commands,
    )
    from examples.models import ExamplesModels, ExamplesModels as m
    from examples.protocols import ExamplesProtocols, ExamplesProtocols as p
    from examples.typings import ExamplesTypes, ExamplesTypes as t
    from examples.utilities import ExamplesUtilities, ExamplesUtilities as u
    from flext_core import FlextTypes
    from flext_core.decorators import FlextDecorators as d
    from flext_core.exceptions import FlextExceptions as e
    from flext_core.handlers import FlextHandlers as h
    from flext_core.mixins import FlextMixins as x
    from flext_core.result import FlextResult as r
    from flext_core.service import FlextService as s

_LAZY_IMPORTS: FlextTypes.LazyImportIndex = {
    "CommandHistory": "examples.ex_08_shell_interaction",
    "ConfigurablePlugin": "examples.ex_07_plugin_system",
    "DataExportPlugin": "examples.ex_07_plugin_system",
    "DataManagerCLI": "examples.ex_11_complete_integration",
    "DataProcessorPlugin": "examples.ex_15_plugin",
    "ExamplePlugin": "examples.ex_15_plugin",
    "ExamplesConstants": "examples.constants",
    "ExamplesModels": "examples.models",
    "ExamplesProtocols": "examples.protocols",
    "ExamplesTypes": "examples.typings",
    "ExamplesUtilities": "examples.utilities",
    "FlextCliGettingStarted": "examples.ex_01_getting_started",
    "InteractiveShell": "examples.ex_08_shell_interaction",
    "LazyDataLoader": "examples.ex_09_performance_optimization",
    "LifecyclePlugin": "examples.ex_07_plugin_system",
    "MyAppPluginManager": "examples.ex_07_plugin_system",
    "ReportGeneratorPlugin": "examples.ex_07_plugin_system",
    "advanced_output_example": "examples.ex_02_output_formatting",
    "apply_environment_overrides": "examples.ex_06_configuration",
    "authenticate_user": "examples.ex_03_interactive_prompts",
    "backup_config_files": "examples.ex_04_file_operations",
    "c": ("examples.constants", "ExamplesConstants"),
    "call_authenticated_api": "examples.ex_05_authentication",
    "complete_auth_workflow": "examples.ex_05_authentication",
    "constants": "examples.constants",
    "convert_and_validate_with_pydantic": "examples.ex_12_pydantic_driven_cli",
    "copy_file_with_verification": "examples.ex_14_advanced_file_formats",
    "create_database_config_from_cli": "examples.ex_12_pydantic_driven_cli",
    "create_processing_summary": "examples.ex_04_file_operations",
    "d": ("flext_core.decorators", "FlextDecorators"),
    "database_setup_wizard": "examples.ex_03_interactive_prompts",
    "delete_database": "examples.ex_03_interactive_prompts",
    "demonstrate_auto_cli_generation": "examples.ex_12_pydantic_driven_cli",
    "demonstrate_caching": "examples.ex_09_performance_optimization",
    "demonstrate_lazy_loading": "examples.ex_09_performance_optimization",
    "demonstrate_nested_models": "examples.ex_12_pydantic_driven_cli",
    "demonstrate_plugin_commands": "examples.ex_15_plugin",
    "deploy_application": "examples.ex_12_pydantic_driven_cli",
    "display_database_results": "examples.ex_02_output_formatting",
    "display_project_structure": "examples.ex_02_output_formatting",
    "display_with_panels": "examples.ex_02_output_formatting",
    "e": ("flext_core.exceptions", "FlextExceptions"),
    "efficient_cli_usage": "examples.ex_09_performance_optimization",
    "efficient_table_display": "examples.ex_09_performance_optimization",
    "ex_01_getting_started": "examples.ex_01_getting_started",
    "ex_02_output_formatting": "examples.ex_02_output_formatting",
    "ex_03_interactive_prompts": "examples.ex_03_interactive_prompts",
    "ex_04_file_operations": "examples.ex_04_file_operations",
    "ex_05_authentication": "examples.ex_05_authentication",
    "ex_06_configuration": "examples.ex_06_configuration",
    "ex_07_plugin_system": "examples.ex_07_plugin_system",
    "ex_08_shell_interaction": "examples.ex_08_shell_interaction",
    "ex_09_performance_optimization": "examples.ex_09_performance_optimization",
    "ex_10_testing_utilities": "examples.ex_10_testing_utilities",
    "ex_11_complete_integration": "examples.ex_11_complete_integration",
    "ex_12_pydantic_driven_cli": "examples.ex_12_pydantic_driven_cli",
    "ex_14_advanced_file_formats": "examples.ex_14_advanced_file_formats",
    "ex_15_plugin": "examples.ex_15_plugin",
    "execute_deploy_from_cli": "examples.ex_12_pydantic_driven_cli",
    "expensive_calculation": "examples.ex_09_performance_optimization",
    "export_data_multi_format": "examples.ex_14_advanced_file_formats",
    "export_database_report": "examples.ex_04_file_operations",
    "export_multi_format": "examples.ex_04_file_operations",
    "export_report": "examples.ex_02_output_formatting",
    "export_to_csv": "examples.ex_14_advanced_file_formats",
    "flext_configuration_wizard": "examples.ex_03_interactive_prompts",
    "flext_confirm_prompts": "examples.ex_03_interactive_prompts",
    "flext_numeric_prompts": "examples.ex_03_interactive_prompts",
    "flext_prompt_with_validation": "examples.ex_03_interactive_prompts",
    "full_workflow_command": "examples.ex_10_testing_utilities",
    "generate_output_files": "examples.ex_04_file_operations",
    "get_cli_settings": "examples.ex_06_configuration",
    "get_saved_token": "examples.ex_05_authentication",
    "get_user_configuration": "examples.ex_03_interactive_prompts",
    "h": ("flext_core.handlers", "FlextHandlers"),
    "handle_config_command": "examples.ex_08_shell_interaction",
    "handle_list_command": "examples.ex_08_shell_interaction",
    "handle_multiline_input": "examples.ex_08_shell_interaction",
    "handle_status_command": "examples.ex_08_shell_interaction",
    "import_from_csv": "examples.ex_14_advanced_file_formats",
    "initialize_services": "examples.ex_06_configuration",
    "interactive_command": "examples.ex_10_testing_utilities",
    "list_project_files": "examples.ex_04_file_operations",
    "load_any_format_file": "examples.ex_14_advanced_file_formats",
    "load_application_config": "examples.ex_06_configuration",
    "load_config_auto_detect": "examples.ex_04_file_operations",
    "load_deployment_config": "examples.ex_04_file_operations",
    "load_environment_config": "examples.ex_06_configuration",
    "load_plugins_from_directory": "examples.ex_07_plugin_system",
    "load_profile_config": "examples.ex_06_configuration",
    "load_user_preferences": "examples.ex_04_file_operations",
    "login_to_service": "examples.ex_05_authentication",
    "logout": "examples.ex_05_authentication",
    "m": ("examples.models", "ExamplesModels"),
    "main": "examples.ex_14_advanced_file_formats",
    "models": "examples.models",
    "monitor_live_metrics": "examples.ex_02_output_formatting",
    "my_cli_command": "examples.ex_10_testing_utilities",
    "p": ("examples.protocols", "ExamplesProtocols"),
    "perform_connection_test": "examples.ex_12_pydantic_driven_cli",
    "process_binary_file": "examples.ex_14_advanced_file_formats",
    "process_file_pipeline": "examples.ex_04_file_operations",
    "process_large_dataset": "examples.ex_09_performance_optimization",
    "process_text_file": "examples.ex_14_advanced_file_formats",
    "process_with_railway_pattern": "examples.ex_11_complete_integration",
    "process_with_status": "examples.ex_02_output_formatting",
    "prompts": "examples.ex_03_interactive_prompts",
    "protocols": "examples.protocols",
    "r": ("flext_core.result", "FlextResult"),
    "refresh_token_if_needed": "examples.ex_05_authentication",
    "risky_operation": "examples.ex_10_testing_utilities",
    "s": ("flext_core.service", "FlextService"),
    "save_config_command": "examples.ex_10_testing_utilities",
    "save_deployment_config": "examples.ex_04_file_operations",
    "save_user_preferences": "examples.ex_04_file_operations",
    "select_environment": "examples.ex_03_interactive_prompts",
    "show_common_cli_params": "examples.ex_12_pydantic_driven_cli",
    "show_config_locations": "examples.ex_06_configuration",
    "show_directory_tree": "examples.ex_04_file_operations",
    "show_environment_variables": "examples.ex_06_configuration",
    "show_session_info": "examples.ex_05_authentication",
    "stream_large_file": "examples.ex_09_performance_optimization",
    "t": ("examples.typings", "ExamplesTypes"),
    "test_cli_command": "examples.ex_10_testing_utilities",
    "test_error_scenarios": "examples.ex_10_testing_utilities",
    "test_file_operations": "examples.ex_10_testing_utilities",
    "test_integration": "examples.ex_10_testing_utilities",
    "test_interactive_command": "examples.ex_10_testing_utilities",
    "typings": "examples.typings",
    "u": ("examples.utilities", "ExamplesUtilities"),
    "utilities": "examples.utilities",
    "validate_and_import_data": "examples.ex_04_file_operations",
    "validate_and_transform_data": "examples.ex_04_file_operations",
    "validate_app_config": "examples.ex_06_configuration",
    "validate_business_rules": "examples.ex_12_pydantic_driven_cli",
    "validate_current_token": "examples.ex_05_authentication",
    "validate_email_input": "examples.ex_03_interactive_prompts",
    "validate_required_fields": "examples.ex_12_pydantic_driven_cli",
    "validate_user_credentials": "examples.ex_05_authentication",
    "x": ("flext_core.mixins", "FlextMixins"),
    "your_cli_function": "examples.ex_02_output_formatting",
}


install_lazy_exports(__name__, globals(), _LAZY_IMPORTS)
