# AUTO-GENERATED FILE — Regenerate with: make gen
"""Lazy-import manifest — single source of truth for flext_cli.__init__.py.

Generated by ``make gen``. The package initializer consumes only this module for
lazy (PEP 562) import access; sibling ``__all__`` discovery is the upstream source.
"""

from __future__ import annotations

LAZY_MODULES: dict[str, tuple[str, ...]] = {
    "._config": ("config",),
    "._settings": ("settings",),
    ".api": ("FlextCli", "cli"),
    ".base": ("FlextCliServiceBase", "s"),
    ".constants": ("FlextCliConstants", "c"),
    ".models": ("FlextCliModels", "m"),
    ".protocols": ("FlextCliProtocols", "p"),
    ".services.auth": ("FlextCliAuth",),
    ".services.cli": ("FlextCliCli",),
    ".services.cli_params": ("FlextCliCommonParams",),
    ".services.cmd": ("FlextCliCmd",),
    ".services.file_tools": ("FlextCliFileTools",),
    ".services.formatters": ("FlextCliFormatters",),
    ".services.output": ("FlextCliOutput",),
    ".services.pipeline": ("FlextCliPipeline",),
    ".services.prompts": ("FlextCliPrompts",),
    ".services.rules": ("FlextCliRules",),
    ".services.runtime": ("FlextCliRuntime",),
    ".services.tables": ("FlextCliTables",),
    ".typings": ("FlextCliTypes", "t"),
    ".utilities": ("FlextCliUtilities", "u"),
    "flext_core._root_typing_parts.facades": ("d", "e", "h", "r", "x"),
}


LAZY_ALIAS_GROUPS: dict[str, tuple[tuple[str, str], ...]] = {}


CHILD_MODULE_PATHS: tuple[str, ...] = (".services",)


EXCLUDED_LAZY_NAMES: tuple[str, ...] = ("_cli_parts",)


PUBLIC_EXPORTS: tuple[str, ...] = (
    "FlextCli",
    "FlextCliAuth",
    "FlextCliCli",
    "FlextCliCmd",
    "FlextCliCommonParams",
    "FlextCliConstants",
    "FlextCliFileTools",
    "FlextCliFormatters",
    "FlextCliModels",
    "FlextCliOutput",
    "FlextCliPipeline",
    "FlextCliPrompts",
    "FlextCliProtocols",
    "FlextCliRules",
    "FlextCliRuntime",
    "FlextCliServiceBase",
    "FlextCliTables",
    "FlextCliTypes",
    "FlextCliUtilities",
    "__author__",
    "__author_email__",
    "__description__",
    "__license__",
    "__title__",
    "__url__",
    "__version__",
    "__version_info__",
    "c",
    "cli",
    "config",
    "d",
    "e",
    "h",
    "m",
    "p",
    "r",
    "s",
    "services",
    "settings",
    "t",
    "u",
    "x",
)
