"""Lazy export registry for src/flext_cli/__init__.py."""

from __future__ import annotations

from flext_core.lazy import build_lazy_import_map, merge_lazy_imports

FLEXT_CLI_METADATA_EXPORTS: tuple[str, ...] = (
    "__author__",
    "__author_email__",
    "__description__",
    "__license__",
    "__title__",
    "__url__",
    "__version__",
    "__version_info__",
)

FLEXT_CLI_LAZY_IMPORTS = merge_lazy_imports(
    (
        "._constants",
        "._models",
        "._protocols",
        "._typings",
        "._utilities",
        ".services",
    ),
    build_lazy_import_map(
        {
            "._constants.base": ("FlextCliConstantsBase",),
            "._constants.enums": ("FlextCliConstantsEnums",),
            "._constants.errors": ("FlextCliConstantsErrors",),
            "._constants.exceptions": ("FlextCliConstantsExceptions",),
            "._constants.files": ("FlextCliConstantsFiles",),
            "._constants.output": ("FlextCliConstantsOutput",),
            "._constants.pipeline": ("FlextCliConstantsPipeline",),
            "._constants.settings": ("FlextCliConstantsSettings",),
            "._models.base": ("FlextCliModelsBase",),
            "._models.pipeline": ("FlextCliModelsPipeline",),
            "._models.rules": ("FlextCliModelsRules",),
            "._protocols.base": ("FlextCliProtocolsBase",),
            "._protocols.domain": ("FlextCliProtocolsDomain",),
            "._protocols.pipeline": ("FlextCliProtocolsPipeline",),
            "._typings.base": ("FlextCliTypesBase",),
            "._typings.domain": ("FlextCliTypesDomain",),
            "._typings.pipeline": ("FlextCliTypesPipeline",),
            "._utilities.auth": ("FlextCliUtilitiesAuth",),
            "._utilities.cmd": ("FlextCliUtilitiesCmd",),
            "._utilities.commands": ("FlextCliUtilitiesCommands",),
            "._utilities.conversion": ("FlextCliUtilitiesConversion",),
            "._utilities.file_test_helpers": ("FlextCliUtilitiesFileTestHelpersMixin",),
            "._utilities.files": ("FlextCliUtilitiesFiles",),
            "._utilities.formatters": ("FlextCliUtilitiesFormatters",),
            "._utilities.json": ("FlextCliUtilitiesJson",),
            "._utilities.matching": ("FlextCliUtilitiesMatching",),
            "._utilities.model_commands": (
                "FlextCliUtilitiesModelCommandBuilder",
                "FlextCliUtilitiesModelCommands",
            ),
            "._utilities.options": (
                "FlextCliUtilitiesOptionBuilder",
                "FlextCliUtilitiesOptions",
            ),
            "._utilities.output": ("FlextCliUtilitiesOutput",),
            "._utilities.params": ("FlextCliUtilitiesParams",),
            "._utilities.pipeline": ("FlextCliUtilitiesPipeline",),
            "._utilities.prompts": ("FlextCliUtilitiesPrompts",),
            "._utilities.rules": ("FlextCliUtilitiesRules",),
            "._utilities.runtime": ("FlextCliUtilitiesRuntime",),
            "._utilities.settings": ("FlextCliUtilitiesSettings",),
            "._utilities.tables": ("FlextCliUtilitiesTables",),
            "._utilities.toml": ("FlextCliUtilitiesToml",),
            "._utilities.validation": ("FlextCliUtilitiesValidation",),
            "._utilities.yaml": ("FlextCliUtilitiesYaml",),
            ".api": (
                "FlextCli",
                "cli",
            ),
            ".base": (
                "FlextCliServiceBase",
                "s",
            ),
            ".constants": (
                "FlextCliConstants",
                "c",
            ),
            ".models": (
                "FlextCliModels",
                "m",
            ),
            ".protocols": (
                "FlextCliProtocols",
                "p",
            ),
            ".services.auth": ("FlextCliAuth",),
            ".services.cli": ("FlextCliCli",),
            ".services.cli_params": ("FlextCliCommonParams",),
            ".services.cmd": ("FlextCliCmd",),
            ".services.file_tools": ("FlextCliFileTools",),
            ".services.formatters": ("FlextCliFormatters",),
            ".services.output": ("FlextCliOutput",),
            ".services.pipeline": ("FlextCliPipeline",),
            ".services.prompts": ("FlextCliPrompts",),
            ".services.rules": ("FlextCliRules",),
            ".services.runtime": ("FlextCliRuntime",),
            ".services.tables": ("FlextCliTables",),
            ".settings": ("FlextCliSettings",),
            ".typings": (
                "FlextCliTypes",
                "t",
            ),
            ".utilities": (
                "FlextCliUtilities",
                "u",
            ),
            "flext_core": (
                "d",
                "e",
                "h",
                "r",
                "x",
            ),
        },
    ),
    exclude_names=(
        "cleanup_submodule_namespace",
        "install_lazy_exports",
        "lazy_getattr",
        "logger",
        "merge_lazy_imports",
        "output",
        "output_reporting",
        "pytest_addoption",
        "pytest_collect_file",
        "pytest_collection_modifyitems",
        "pytest_configure",
        "pytest_runtest_setup",
        "pytest_runtest_teardown",
        "pytest_sessionfinish",
        "pytest_sessionstart",
        "pytest_terminal_summary",
        "pytest_warning_recorded",
    ),
    module_name=__name__.rsplit(".", maxsplit=1)[0],
)

FLEXT_CLI_PUBLIC_EXPORTS: tuple[str, ...] = (
    "FlextCli",
    "FlextCliAuth",
    "FlextCliCli",
    "FlextCliCmd",
    "FlextCliCommonParams",
    "FlextCliConstants",
    "FlextCliFileTools",
    "FlextCliFormatters",
    "FlextCliModels",
    "FlextCliOutput",
    "FlextCliPipeline",
    "FlextCliPrompts",
    "FlextCliProtocols",
    "FlextCliRules",
    "FlextCliRuntime",
    "FlextCliServiceBase",
    "FlextCliSettings",
    "FlextCliTables",
    "FlextCliTypes",
    "FlextCliUtilities",
    "__author__",
    "__author_email__",
    "__description__",
    "__license__",
    "__title__",
    "__url__",
    "__version__",
    "__version_info__",
    "c",
    "cli",
    "d",
    "e",
    "h",
    "m",
    "p",
    "r",
    "s",
    "t",
    "u",
    "x",
)

__all__: list[str] = [
    "FLEXT_CLI_LAZY_IMPORTS",
    "FLEXT_CLI_METADATA_EXPORTS",
    "FLEXT_CLI_PUBLIC_EXPORTS",
]
